import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Toaster } from 'react-hot-toast';
import NavBat from './NavBar';
import SideBar from './SideBar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster />
        <NavBat />
        <div className='grid grid-cols-6 h-screen'>
          <div className='col-span-1 border-r-[1.3px]'>
            <SideBar />
          </div>
          <div className='col-span-5 p-3'> {children}</div>
        </div>
      </body>
    </html>
  );
}
